#!/usr/bin/env bash
# Write client/web/*/.env.production for Docker `next build`.
# Next.js only inlines NEXT_PUBLIC_* from .env.production when NODE_ENV=production during build.
# Usage: bash deploy/vps/scripts/write-web-env-production.sh dev|prod
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT"

ENV_NAME="${1:-}"
if [[ "$ENV_NAME" != "dev" && "$ENV_NAME" != "prod" ]]; then
  echo "Usage: $0 dev|prod"
  exit 1
fi

COMPOSE_ENV="deploy/vps/compose/.env.${ENV_NAME}"
[[ -f "$COMPOSE_ENV" ]] || { echo "Missing $COMPOSE_ENV — run apply-env.sh $ENV_NAME first"; exit 1; }

# shellcheck source=/dev/null
set -a
source "$COMPOSE_ENV"
set +a

URL="${NEXT_PUBLIC_SUPABASE_URL:-}"
FUN="${NEXT_PUBLIC_FUNCTIONS_URL:-}"
ANON="${NEXT_PUBLIC_SUPABASE_ANON_KEY:-${ANON_KEY:-}}"
APP_ENV="${NEXT_PUBLIC_APP_ENV:-development}"

if [[ -z "$URL" ]]; then
  echo "NEXT_PUBLIC_SUPABASE_URL missing in $COMPOSE_ENV"
  exit 1
fi
if [[ -z "$FUN" ]]; then
  FUN="${URL%/}/functions/v1"
fi
if [[ -z "$ANON" || "$ANON" == REPLACE_* ]]; then
  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY missing (run apply-env.sh after server/supabase/.env has ANON_KEY)"
  exit 1
fi

MAPS_KEY=""
if [[ -f server/supabase/.env ]]; then
  MAPS_KEY="$(grep '^GOOGLE_MAPS_API_KEY=' server/supabase/.env 2>/dev/null | cut -d= -f2- | tr -d "'\"" | head -1 || true)"
fi
if [[ -z "$MAPS_KEY" || "$MAPS_KEY" == REPLACE_* ]]; then
  MAPS_KEY="${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY:-}"
fi
if [[ -z "$MAPS_KEY" || "$MAPS_KEY" == REPLACE_* ]]; then
  for f in client/web/ryvo_admin/.env.local client/web/ryvo/.env.local deploy/vps/client/web/ryvo_admin/env.${ENV_NAME}.example deploy/vps/client/web/ryvo/env.${ENV_NAME}.example; do
    if [[ -f "$f" ]]; then
      val="$(grep '^NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=' "$f" 2>/dev/null | cut -d= -f2- | tr -d "'\"" | head -1 || true)"
      [[ -n "$val" && "$val" != REPLACE_* ]] && MAPS_KEY="$val" && break
    fi
  done
fi

write_one() {
  local app_dir="$1"
  local outfile="$ROOT/$app_dir/.env.production"
  cat >"$outfile" <<EOF
# Generated by deploy/vps/scripts/write-web-env-production.sh ($ENV_NAME)
# Next.js reads this file during next build (production mode). Do not commit.
NEXT_PUBLIC_SUPABASE_URL=${URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON}
NEXT_PUBLIC_FUNCTIONS_URL=${FUN}
NEXT_PUBLIC_APP_ENV=${APP_ENV}
EOF
  if [[ -n "$MAPS_KEY" && "$MAPS_KEY" != REPLACE_* ]]; then
    echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${MAPS_KEY}" >>"$outfile"
  fi
  echo "  wrote $outfile"
}

echo "==> write-web-env-production ($ENV_NAME)"
write_one "client/web/ryvo_admin"
write_one "client/web/ryvo"
echo "==> done"
