#!/usr/bin/env bash
# Create server/*/.env from .env.example when missing (never overwrites existing).
# Derives compose/local.env + client/web/*/.env.local + .env.production from server/supabase/.env.
# See docs/env-guide.md
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

copy_if_missing() {
  local dir="$1"
  if [[ ! -f "${dir}/.env" ]]; then
    if [[ -f "${dir}/.env.example" ]]; then
      cp "${dir}/.env.example" "${dir}/.env"
      echo "Created ${dir}/.env from .env.example"
    else
      echo "WARN: No .env.example in ${dir}"
    fi
  fi
}

copy_if_missing "${ROOT}/server/supabase"
copy_if_missing "${ROOT}/server/kafka"
copy_if_missing "${ROOT}/server/redis"
copy_if_missing "${ROOT}/server/bunqueue"

# Client env (local): populate Supabase URL + anon key from server/supabase/.env
SUPABASE_ENV="${ROOT}/server/supabase/.env"
read_kv() {
  local file="$1" key="$2"
  grep -E "^${key}=" "$file" 2>/dev/null | head -n1 | cut -d= -f2- | sed "s/^['\"]//;s/['\"]$//"
}

patch_kv() {
  local file="$1" key="$2" value="$3"
  [[ -f "$file" ]] || touch "$file"
  if grep -qE "^${key}=" "$file" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$file"
  else
    echo "${key}=${value}" >>"$file"
  fi
}

if [[ -f "$SUPABASE_ENV" ]]; then
  mkdir -p "${ROOT}/compose"
  if [[ ! -f "${ROOT}/compose/local.env" && -f "${ROOT}/compose/local.env.example" ]]; then
    cp "${ROOT}/compose/local.env.example" "${ROOT}/compose/local.env"
    echo "Created compose/local.env from compose/local.env.example"
  fi
  if [[ -f "${ROOT}/.env" && ! -f "${ROOT}/compose/local.env" ]]; then
    cp "${ROOT}/.env" "${ROOT}/compose/local.env"
    echo "Migrated root .env -> compose/local.env (root .env is deprecated)"
  fi
  if [[ -f "${ROOT}/.env" && -f "${ROOT}/compose/local.env" ]]; then
    rm -f "${ROOT}/.env"
    echo "Removed deprecated root .env (use compose/local.env — see docs/env-guide.md)"
  fi

  for app in ryvo ryvo_admin; do
    local_env="${ROOT}/client/web/${app}/.env.local"
    if [[ ! -f "$local_env" && -f "${ROOT}/client/web/${app}/.env.example" ]]; then
      cp "${ROOT}/client/web/${app}/.env.example" "$local_env"
      echo "Created client/web/${app}/.env.local from .env.example"
    fi
  done

  anon="$(read_kv "$SUPABASE_ENV" "ANON_KEY")"
  maps="$(read_kv "$SUPABASE_ENV" "GOOGLE_MAPS_API_KEY")"
  pub_url="$(read_kv "$SUPABASE_ENV" "SUPABASE_PUBLIC_URL")"
  # Local defaults: hit Caddy -> Kong on 8400
  local_url="http://localhost:8400"
  functions_url="http://localhost:8400/functions/v1"

  for f in \
    "${ROOT}/client/web/ryvo/.env.local" \
    "${ROOT}/client/web/ryvo_admin/.env.local" \
    "${ROOT}/compose/local.env"; do
    # For local dev, always point to localhost (Supabase/Kong is exposed via Caddy on 8400).
    patch_kv "$f" "NEXT_PUBLIC_SUPABASE_URL" "${local_url}"
    patch_kv "$f" "NEXT_PUBLIC_FUNCTIONS_URL" "${functions_url}"
    [[ -n "${anon:-}" ]] && patch_kv "$f" "NEXT_PUBLIC_SUPABASE_ANON_KEY" "${anon}"
    [[ -n "${maps:-}" ]] && patch_kv "$f" "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY" "${maps}"
    patch_kv "$f" "NEXT_PUBLIC_APP_ENV" "development"
  done

  # Docker `next build` reads .env.production (not .env.local). Mirror dev values for local image builds.
  for app in ryvo_admin ryvo; do
    prod="${ROOT}/client/web/${app}/.env.production"
    {
      echo "# Generated by scripts/ensure-env.sh — used by Docker next build"
      echo "NEXT_PUBLIC_SUPABASE_URL=${local_url}"
      echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}"
      echo "NEXT_PUBLIC_FUNCTIONS_URL=${functions_url}"
      echo "NEXT_PUBLIC_APP_ENV=development"
      [[ "$app" == "ryvo_admin" && -n "${maps:-}" ]] && echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${maps}"
    } >"$prod"
    echo "Wrote ${prod}"
  done
fi

# PostgREST/database URLs break when POSTGRES_PASSWORD contains '@' — set encoded form.
if [[ -f "$SUPABASE_ENV" ]] && grep -q '^POSTGRES_PASSWORD=' "$SUPABASE_ENV"; then
  pw="$(grep '^POSTGRES_PASSWORD=' "$SUPABASE_ENV" | cut -d= -f2- | sed "s/^['\"]//;s/['\"]$//")"
  enc="$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=''))" "$pw")"
  if grep -q '^POSTGRES_PASSWORD_URI_ENCODED=' "$SUPABASE_ENV"; then
    sed -i "s|^POSTGRES_PASSWORD_URI_ENCODED=.*|POSTGRES_PASSWORD_URI_ENCODED=${enc}|" "$SUPABASE_ENV"
  else
    echo "POSTGRES_PASSWORD_URI_ENCODED=${enc}" >> "$SUPABASE_ENV"
  fi
fi
