export const env = {
  jwtSecret: process.env.JWT_SECRET ?? "",
  supabaseUrl: process.env.SUPABASE_URL ?? "http://kong:8000",
  supabasePublicUrl: process.env.SUPABASE_PUBLIC_URL ?? "http://localhost:8400",
  serviceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  anonKey: process.env.SUPABASE_ANON_KEY ?? "",
  redisUrl: process.env.REDIS_URL ?? "redis://ryvo_redis:6379",
  kafkaBroker: process.env.KAFKA_BROKER ?? "ryvo_kafka_broker:9092",
  bunqueueHost: process.env.BUNQUEUE_HOST ?? "ryvo_bunqueue",
  bunqueuePort: Number(process.env.BUNQUEUE_PORT ?? 6789),
  serviceHmacSecret: process.env.SERVICE_HMAC_SECRET ?? "ryvo-dev-hmac-secret-change-me",
  googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  port: Number(process.env.PORT ?? 9000),
  nodeEnv: process.env.NODE_ENV ?? "development",
  smtpHost: process.env.SMTP_HOST ?? "smtp.freesmtpservers.com",
  smtpPort: Number(process.env.SMTP_PORT ?? 25),
  smtpUser: process.env.SMTP_USER ?? "",
  smtpPass: process.env.SMTP_PASS ?? "",
  smtpFrom: process.env.SMTP_ADMIN_EMAIL ?? "no-reply@ryvo-line.com",
  smtpSenderName: process.env.SMTP_SENDER_NAME ?? "Ryvo",
  mailerOtpExpSec: Number(process.env.MAILER_OTP_EXP ?? 1800),
};
