import type { RouteDef } from "../../../../_shared/core/router.ts";
import {
  get_v1_admin_finance_referrals_settings,
  patch_v1_admin_finance_referrals_settings,
  get_v1_admin_finance_referrals,
  get_v1_admin_finance_referrals_bonuses,
  post_v1_admin_finance_referrals_bonuses,
  patch_v1_admin_finance_referrals_bonuses_id,
  delete_v1_admin_finance_referrals_bonuses_id,
  post_v1_admin_finance_referrals_loyalty,
  post_v1_admin_finance_referrals_campaigns,
  patch_v1_admin_finance_referrals_campaigns_id,
  delete_v1_admin_finance_referrals_campaigns_id,
} from "./controller.ts";

export const routes: RouteDef[] = [
  {
    method: "GET",
    path: "/v1/admin/finance/referrals/settings",
    auth: true,
    permissions: ["finances:referrals:read"],
    handler: get_v1_admin_finance_referrals_settings,
  },
  {
    method: "PATCH",
    path: "/v1/admin/finance/referrals/settings",
    auth: true,
    permissions: ["finances:referrals:update"],
    handler: patch_v1_admin_finance_referrals_settings,
  },
  {
    method: "GET",
    path: "/v1/admin/finance/referrals",
    auth: true,
    permissions: ["finances:referrals:read"],
    handler: get_v1_admin_finance_referrals,
  },
  {
    method: "GET",
    path: "/v1/admin/finance/referrals/bonuses",
    auth: true,
    permissions: ["finances:referrals:read"],
    handler: get_v1_admin_finance_referrals_bonuses,
  },
  {
    method: "POST",
    path: "/v1/admin/finance/referrals/bonuses",
    auth: true,
    permissions: ["finances:referrals:update"],
    handler: post_v1_admin_finance_referrals_bonuses,
  },
  {
    method: "PATCH",
    path: "/v1/admin/finance/referrals/bonuses/:id",
    auth: true,
    permissions: ["finances:referrals:update"],
    handler: patch_v1_admin_finance_referrals_bonuses_id,
  },
  {
    method: "DELETE",
    path: "/v1/admin/finance/referrals/bonuses/:id",
    auth: true,
    permissions: ["finances:referrals:update"],
    handler: delete_v1_admin_finance_referrals_bonuses_id,
  },
  {
    method: "POST",
    path: "/v1/admin/finance/referrals/loyalty",
    auth: true,
    permissions: ["finances:referrals:update"],
    handler: post_v1_admin_finance_referrals_loyalty,
  },
  {
    method: "POST",
    path: "/v1/admin/finance/referrals/campaigns",
    auth: true,
    permissions: ["finances:referrals:update"],
    handler: post_v1_admin_finance_referrals_campaigns,
  },
  {
    method: "PATCH",
    path: "/v1/admin/finance/referrals/campaigns/:id",
    auth: true,
    permissions: ["finances:referrals:update"],
    handler: patch_v1_admin_finance_referrals_campaigns_id,
  },
  {
    method: "DELETE",
    path: "/v1/admin/finance/referrals/campaigns/:id",
    auth: true,
    permissions: ["finances:referrals:update"],
    handler: delete_v1_admin_finance_referrals_campaigns_id,
  },
];
